spring.application.name=spring-security-project

spring.security.user.name=spring
spring.security.user.password=1234

spring.datasource.url=jdbc:postgresql://localhost:5432/telusko
spring.datasource.username=postgres
spring.datasource.password=1234

spring.jpa.hibernate.ddl-auto=update

server.servlet.session.cookie.same-site=strict