create table users (
	id int primary key GENERATED BY DEFAULT AS IDENTITY,
	username varchar(250),
	password varchar(250)
);

insert into users (id, username, password) values
(1123123, 'johnjohn', '9876'),
(2123123, 'joejoe', '9876543');